In [2]:
#conditinal cased choices

#where
import numpy as np
arr = np.array([1,2,3])



In [3]:
arr

array([1, 2, 3])

In [6]:
result = np.where(arr<3,"low","high")

In [7]:
result

array(['low', 'low', 'high'], dtype='<U4')

In [4]:
import numpy as np
arr = np.array([10, 60, 30, 80])
mask = arr > 50    # [False, True, False, True]

print(arr[mask])
# [60, 80]


arr1 = np.array([10, 40, 60, 80])

mask = arr1 > 50
print(mask)


[60 80]
[False False  True  True]


In [13]:
#argwhere : row- column position for 2d array

arr = np.array([10,25,35,50])
arr

array([10, 25, 35, 50])

In [14]:
print(np.argwhere(arr>0))

[[0]
 [1]
 [2]
 [3]]


In [17]:
print(np.argwhere(arr>35))

[[3]]


In [34]:
import numpy as np
arr = np.array([10, 60, 30, 80])

# Get positions where arr > 50
print(np.where(arr > 50))      # (array([1, 3]),)

# Apply if-else
print(np.where(arr > 50, "Pass", "Fail"))
# ['Fail' 'Pass' 'Fail' 'Pass']


(array([1, 3], dtype=int64),)
['Fail' 'Pass' 'Fail' 'Pass']


In [35]:
#np.take()
import numpy as np

arr = np.array([5, 10, 15, 20])

result = np.take(arr, [0, 2])
print(result)


[ 5 15]


In [16]:
mask = np.logical_and(arr>15,arr<35)

In [18]:
mask


array([False,  True, False, False])

In [19]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [22]:
#logical and
arr = np.array([1,4,6,85,33,22,76])


In [23]:
arr

array([ 1,  4,  6, 85, 33, 22, 76])

In [24]:
mask = np.logical_and(arr>3,arr<6)

In [25]:
mask

array([False,  True, False, False, False, False, False])

In [26]:
arr[mask]

array([4])

In [27]:
#logical or
mask = np.logical_or(arr<4,arr>5)


In [28]:
mask

array([ True, False,  True,  True,  True,  True,  True])

In [29]:
arr[mask]

array([ 1,  6, 85, 33, 22, 76])

In [31]:
arr2=np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [32]:
print(np.nonzero(arr2))

(array([1, 2, 4], dtype=int64),)


In [5]:
import numpy as np

arr = np.array([10, 40, 60, 80, 25])

result = arr[np.logical_and(arr > 30, arr < 70)]
print(result)


[40 60]


In [6]:
import numpy as np

arr = np.array([10, 40, 60, 80, 25])

result = arr[np.logical_or(arr < 20, arr > 70)]
print(result)


[10 80]
