In [2]:
import numpy as np
a = np.array([3,4,5])
b =np.array([6,7,8])


In [3]:
print(a+b)


[ 9 11 13]


In [4]:
#subtrcation
print(a-b)

[-3 -3 -3]


In [5]:
#division
print(a/b)

[0.5        0.57142857 0.625     ]


In [8]:
print(b//a)

[2 1 1]


In [6]:
#multi
print(a*b)

[18 28 40]


In [10]:
#moduls
print(b%a)

[0 3 3]
