In [2]:

import numpy as np
#transpose of matrix
arr = np.array([[1,2],[3,4]])
arr


array([[1, 2],
       [3, 4]])

In [3]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [40]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])       # shape (2,3)

print("A shape:", A.shape)
print("A:\n", A)

At = A.T                    # transpose
print("\nA.T shape:", At.shape)
print("A.T:\n", At)


A shape: (2, 3)
A:
 [[1 2 3]
 [4 5 6]]

A.T shape: (3, 2)
A.T:
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
#swapaxes -> swap 2 specific axes
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [6]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [42]:
A = np.array([[1,2,3],
              [4,5,6]])   # shape (2,3)
print(np.swapaxes(A, 0, 1).shape)


(3, 2)


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#concatination
a = np.array([1,2])
b = np.array([3,4])


In [8]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [9]:
#vertical stack
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])


In [10]:
print(np.vstack((arr1,arr2)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
#h=-stack
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
print(np.stack((arr1,arr2),axis =0))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(np.stack((arr1,arr2),axis =1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [14]:
#splitting the array
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])


In [15]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
print(np.split(arr1,3))

ValueError: array split does not result in an equal division

In [20]:
print(np.split(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [21]:
#repeating
arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [22]:
#tile -> repeat my whole array
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [24]:
#Aggregate function:

arr = np.array([1,2,3])
print(np.sum(arr))
      

6


In [25]:
np.mean(arr)

2.0

In [26]:
np.median(arr)

2.0

In [27]:
np.std(arr)

0.816496580927726

In [28]:
np.var(arr)

0.6666666666666666

In [29]:
np.min(arr)

1

In [30]:
np.max(arr)

3

In [32]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(np.sum(m,axis=1))

[ 6 15 24]


In [35]:
print(np.sum(m,axis=0))

[12 15 18]


In [36]:
#Cumulative opeartion -> running total

arr

array([1, 2, 3])

In [37]:
print(np.cumsum(arr))

[1 3 6]


In [39]:
print(np.cumprod(arr))

[1 2 6]


In [ ]:
###condintional
