In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))


[1 2 3 4 5]
Sum: 15
Mean: 3.0


In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))


[1 2 3 4 5]
Sum: 15
Mean: 3.0


In [28]:
arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

In [75]:
a = np.array(421)
a.ndim
a.shape
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.shape)


(5,)


In [41]:
arr1 = np.array([32,3,23])
arr2 = np.array([[54,3,33],[42,56,32]])
arr3 = np.array([[3,4,5],[3,6,7],[53,4,2]])
print(arr3)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

[[ 3  4  5]
 [ 3  6  7]
 [53  4  2]]
(3,)
(2, 3)
(3, 3)


In [44]:
a = np.array(223)
print(a.shape)
print(a.ndim)

()
0


In [47]:
a1 = np.arange(1,10)
a1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a2 = np.arange(1,10,2)#start end step
a2

array([1, 3, 5, 7, 9])

In [51]:
a1 = np.linspace(0,5,5)
a1

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [52]:
a3 = np.linspace(1,4,5) #start stop num of values between them
a3

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [56]:
a1 = np.logspace(1,1,2) #logarithmic scale array ->10^1 -->10^3 
# np.lodspace(start,ending ->,3->number of number of values)
a1

array([10., 10.])

In [57]:
#np.zeros --> array full if zeros
arr = np.zeros(5)
arr


array([0., 0., 0., 0., 0.])

In [58]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
arr = np.ones([4,2]) #by default is float #array full of ones
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
arr = np.full(10,2) #craete an array full of any values
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
arr = np.full([2,4],5) # [row col],default value
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [76]:
#np.empty #Uninitialized array -> create anarray without any value
arr = np.empty([2,3])
arr
arr_empty = np.empty((2, 3))
print("Empty array:\n", arr_empty)

Empty array:
 [[-1.04398319 -0.0198146   0.92937912]
 [-0.30301759  0.1693436   0.02384064]]


In [69]:
arr =np.random.rand(2,3)# not use square brakets here
arr #->random floats(0 to 1)

array([[0.53140411, 0.03264313, 0.61839822],
       [0.53714793, 0.86989956, 0.10489298]])

In [70]:
arr = np.random.randn(2,3)  #->
arr

array([[-1.04398319, -0.0198146 ,  0.92937912],
       [-0.30301759,  0.1693436 ,  0.02384064]])

In [74]:
arr = np.random.randint(10,100)
print(arr) #random integer
arr1 = np.random.randint(10,100,size=(2,3))
print(arr1)

44
[[84 76 64]
 [80 33 51]]
