In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.4


In [14]:
arr = np.array([23])
arr1 = np.array(23)

In [16]:
print(arr)
print(arr1)

[23]
23


In [18]:
print(type(arr))
print(type(arr1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
print(arr.shape)

(1,)


In [19]:
print(arr1.shape)

()


In [20]:
arr1.dtype

dtype('int32')

In [25]:
arr.size

1

In [26]:
arr1.ndim

0

In [27]:
arr.ndim

1

In [31]:
arr2 = np.array([23,45],dtype ="f")
arr2

array([23., 45.], dtype=float32)

In [32]:
arr2.dtype

dtype('float32')

In [39]:
arr3 = np.array([21.3,22],dtype = 'S')
arr3.dtype

dtype('S4')

In [40]:
arr3

array([b'21.3', b'22'], dtype='|S4')

In [41]:
arr3.itemsize

4

In [42]:
arr2.itemsize

4

In [53]:
a2 = np.arange(0,10,7)
a2

array([0, 2, 4, 6, 8])

In [54]:
a1 = np.linspace(0,10,5,dtype = "i")
a1

array([ 0,  2,  5,  7, 10], dtype=int32)

In [45]:
a1.dtype

dtype('float64')

In [46]:
type(a1)

numpy.ndarray

In [47]:
a1.ndim

1

In [48]:
a1.shape

(5,)

In [103]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50], dtype=np.int64)

print("Array:", arr)
print("Size:", arr.size)         # Number of elements
print("Itemsize:", arr.itemsize) # Bytes per element
print("Total bytes (nbytes):", arr.nbytes)  # Total memory used


Array: [10 20 30 40 50]
Size: 5
Itemsize: 8
Total bytes (nbytes): 40


In [55]:
a3 = np.linspace(0,2,3)#by default always float #include last value
a3

array([0., 1., 2.])

In [57]:
a4 = np.logspace(1,3,2,base = 2)
a4

array([2., 8.])

In [59]:
b1=np.zeros((2,3))
b1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
b2 = np.ones([2,5])
b2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
b3= np.full([3,4],3)
b3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

b3= np.full(2,5)

In [64]:
b3= np.full((2,5),4)
b3

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [65]:
b3 = np.full(3,6)
b3

array([6, 6, 6])

In [96]:
b4 = np.empty((2,3))
b4

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.33646676e-307, 2.67018777e-306, 2.42092166e-322]])

In [66]:
n1 = np.array([2,3,4,1,2])
n1

array([2, 3, 4, 1, 2])

In [67]:
n1.ndim

1

In [68]:
n1.dtype


dtype('int32')

In [69]:
n1.shape

(5,)

In [70]:
n1.itemsize

4

In [76]:
n2 = np.array([[12,3],[3,4]],dtype = "f")

In [77]:
n2

array([[12.,  3.],
       [ 3.,  4.]], dtype=float32)

In [78]:
n2.ndim

2

In [79]:
n2.shape

(2, 2)

In [80]:
n2.dtype

dtype('float32')

In [91]:
n3 = np.array([
    [[2,3],[4,6]],
    [[5,8],[7,8]
        
    ]
])

In [92]:
n3

array([[[2, 3],
        [4, 6]],

       [[5, 8],
        [7, 8]]])

In [93]:
n3.ndim

3

In [94]:
n3.dtype

dtype('int32')

In [95]:
n3.shape

(2, 2, 2)

In [97]:
arr =np.random.rand(2,3)# not use square brakets here
arr #->random floats(0 to 1)

array([[0.20367464, 0.90587667, 0.6551628 ],
       [0.71099126, 0.74337374, 0.74044061]])

In [98]:
arr = np.random.randn(2,3)  #->
arr

array([[-0.0277253 , -0.61986747,  0.47948969],
       [ 0.08411657, -0.26453039,  0.41215949]])

In [99]:
arr = np.random.randint(10,100)
print(arr) #random integer
arr1 = np.random.randint(10,100,size=(2,3)) #low,high size =()
print(arr1)

68
[[31 97 55]
 [85 35 89]]


In [100]:
a1 = np.random.rand(3,4)
a1

array([[0.07346779, 0.39798317, 0.34853542, 0.95735665],
       [0.97348714, 0.46613788, 0.34881956, 0.30484525],
       [0.65567772, 0.80008116, 0.35003315, 0.2738754 ]])

In [101]:
a2 = np.random.randn(3,7)
a2

array([[ 1.93988246,  0.42191846,  0.13570501, -0.40213713,  0.23426994,
        -0.91743221,  1.07710563],
       [ 0.79919604, -1.10211863,  0.46864344, -1.23662062, -0.70900261,
         1.58840611,  0.73976491],
       [ 1.42384606, -1.08327212,  0.37050157, -0.03142111, -0.50572329,
        -1.83480712,  0.6202379 ]])

In [102]:
a3 = np.random.randint(2,40,size = (2,3))
a3

array([[29, 36, 20],
       [12,  8, 31]])

In [104]:
import numpy as np

# String array
arr_str = np.array(["10", "20", "30"])
print("Before:", arr_str, arr_str.dtype)

# Convert string to int
arr_int = arr_str.astype(float)
print("After:", arr_int, arr_int.dtype)

Before: ['10' '20' '30'] <U2
After: [10. 20. 30.] float64
