In [13]:
#reshape
import numpy as np

a1 = np.array([[1,2,4],[3,4,5]])
n_arr = a1.reshape(3,2)
n_arr

array([[1, 2],
       [4, 3],
       [4, 5]])

In [14]:
arr = a1.ravel() 
arr

array([1, 2, 4, 3, 4, 5])

In [15]:
n1 = np.array([2,3,4,5,6,7])
n2= n1.reshape(3,2)
n2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [16]:
n3 = n2.ravel()

In [17]:
n3

array([2, 3, 4, 5, 6, 7])

In [19]:
r1 = np.array([[2,3,4],[4,7,9]])
r2 = r1.ravel()
r2

array([2, 3, 4, 4, 7, 9])

In [20]:
r2[2]=45
r2

array([ 2,  3, 45,  4,  7,  9])

In [21]:
r1 # so it effect to the original array

array([[ 2,  3, 45],
       [ 4,  7,  9]])

In [22]:
f1 = np.array([[2,3,4],[3,4,5]])
f1

array([[2, 3, 4],
       [3, 4, 5]])

In [23]:
f2 = f1.flatten()
f2

array([2, 3, 4, 3, 4, 5])

In [24]:
f2[3]=23
f2

array([ 2,  3,  4, 23,  4,  5])

In [25]:
f1 #here it is not affected on original

array([[2, 3, 4],
       [3, 4, 5]])

In [26]:
s1 =np.array([3,5,7,8])
print(np.sqrt(s1))

[1.73205081 2.23606798 2.64575131 2.82842712]


In [27]:
#exponential - > np.exp -> e^x ->x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [28]:
#sine function -> np.sin
angles  = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [29]:
print(np.sin(np.pi/2))

1.0


In [30]:
a1 =[2,3,5,2]


In [31]:
a1

[2, 3, 5, 2]

In [37]:
a1[0:]

[2, 3, 5, 2]

In [38]:
a1[2]

5

In [39]:
a1[3:]

[2]

In [40]:
a1[:]

[2, 3, 5, 2]

In [41]:
a1[:0]

[]

In [42]:
a1[:3]

[2, 3, 5]

In [43]:
a1[:-3]

[2]

In [44]:
a1[-1:-3]

[]

In [45]:
matrix = np.array([
    [1, 2, 3],   # row 0
    [4, 5, 6],   # row 1
    [7, 8, 9]    # row 2
])

In [46]:
matrix[0]

array([1, 2, 3])

In [48]:
matrix[2]

array([7, 8, 9])

In [49]:
matrix[1]

array([4, 5, 6])

In [50]:
# Selecting a COLUMN
#Use : for all rows.
matrix[:,2]

array([3, 6, 9])

In [51]:
matrix[:, 0]   # column 0


array([1, 4, 7])

In [52]:
#  Selecting a SINGLE ELEMENT

# Format: [row, column]

matrix[1, 2]



6

In [54]:
matrix[2,1]

8

In [55]:
# Slicing part of the matrix (sub-matrix)
# ✔ Example: First 2 rows
matrix[0:2, :]


array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# ✔ Example: First 2 columns
matrix[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
#  5. Middle block (5,6,8,9)
matrix[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [59]:
matrix.diagonal()


array([1, 5, 9])

In [60]:
matrix[:, 1]


array([2, 5, 8])

In [61]:
matrix[0, :]


array([1, 2, 3])

In [62]:
# matrix[r1:r2, c1:c2]
# means:

# Take rows from r1 to r2-1
# Take columns from c1 to c2-1



matrix[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
# [::-1] → reverse
# [:, ::-1] → reverse columns
# [::-1, :] → reverse rows

