In [2]:
import numpy as np
#array reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [4]:
reshape_2 = reshaped.reshape(3,2)
reshape_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
#revel -> convert 1d array
ravel = reshape_2.ravel()
print(ravel)
ravel[0]=100
print(ravel)
print(reshape_2)

[100   2   3   4   5   6]
[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [12]:
#flatten -> to 1d array
# returns a copy of the array
flat = reshape_2.flatten()
flat


array([100,   2,   3,   4,   5,   6])

In [13]:
flat[0]=1

In [14]:
flat

array([1, 2, 3, 4, 5, 6])

In [15]:
reshape_2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

r = arr.ravel()
print("Original array:\n", arr)
print("Raveled array:", r)

# Change raveled value
r[0] = 99
print("\nAfter modifying ravel():")
print("Raveled array:", r)
print("Original array:\n", arr)   # original changes


Original array:
 [[1 2 3]
 [4 5 6]]
Raveled array: [1 2 3 4 5 6]

After modifying ravel():
Raveled array: [99  2  3  4  5  6]
Original array:
 [[99  2  3]
 [ 4  5  6]]


In [2]:
import numpy as np

arr = np.array([[[1, 2],
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]]])

r = arr.ravel()
print("Raveled 3D array:", r)

r[3] = 100
print("\nAfter modifying ravel():")
print("Original 3D array:\n", arr)   # original changes

# ravel() gives a view

# Changing r also changes arr

Raveled 3D array: [1 2 3 4 5 6 7 8]

After modifying ravel():
Original 3D array:
 [[[  1   2]
  [  3 100]]

 [[  5   6]
  [  7   8]]]


In [3]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

f = arr.flatten()
print("Original array:\n", arr)
print("Flattened array:", f)

# Modify flattened array
f[1] = 999
print("\nAfter modifying flatten():")
print("Flattened array:", f)
print("Original array:\n", arr)   # original does NOT change


Original array:
 [[10 20 30]
 [40 50 60]]
Flattened array: [10 20 30 40 50 60]

After modifying flatten():
Flattened array: [ 10 999  30  40  50  60]
Original array:
 [[10 20 30]
 [40 50 60]]


In [6]:
import numpy as np

arr = np.array([[[1, 2],
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]]])

f = arr.flatten()
print("Flattened 3D array:", f)

# modify
f[0] = 111
print("\nAfter modifying flatten():")
print("Original 3D array:\n", arr)
# original does NOT change
print(f)
print(arr)


Flattened 3D array: [1 2 3 4 5 6 7 8]

After modifying flatten():
Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[111   2   3   4   5   6   7   8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
