In [18]:
import numpy as np
arr = np.array([1,4,64,16])


In [19]:
# square root -> np.sqrt()
print(np.sqrt(arr))

[1. 2. 8. 4.]


In [20]:
#exponential - > np.exp -> e^x ->x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [21]:
#sine function -> np.sin
angles  = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [50]:
print(np.sin(np.pi))

1.2246467991473532e-16


In [55]:
a = [1,2,3,4,5]
a[-1:-3]


[]

In [54]:
a[-1:-3]#This direction is impossible.

[]

In [56]:
a = [1,2,3,4,5]
a[1:4]    # [2,3,4]    (forward)
a[4:1]    # []         (forward but start > end -> empty)
a[4:1:-1] # [5,4,3]    (backward using negative step)


[5, 4, 3]

In [24]:
a[-1:-4:-1]

[5, 4, 3]

In [25]:
a[::2]

[1, 3, 5]

In [26]:
arr = np.array([10,20,30,40,50])
arr[::2] #slicing

array([10, 30, 50])

In [27]:
arr[-1]

50

In [28]:
print(arr[-1])

50


In [29]:
arr[-5]

10

In [30]:
arr[-1:-5]

array([], dtype=int32)

In [31]:
arr[-1:-4]

array([], dtype=int32)

In [32]:
arr[-1:-3]

array([], dtype=int32)

In [33]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


In [34]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [35]:
print(matrix[1:3 ,:])

[[4 5 6]
 [7 8 9]]


In [36]:
print(matrix[1: ,1:])

[[5 6]
 [8 9]]


In [37]:
#np.take -> bulit in function  to perrom indexing and slicing
arr= np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr,ind))


[10 30]


In [38]:
#iterating with  nditer()
arr = np.array([[1,2],[3,4]])


In [39]:
for x in np.nditer(arr):
    print(x,end = " ")

1 2 3 4 

In [40]:
# ndenumerate() -> both index +value
for ind, x in np.ndenumerate(arr):
    print(ind, x)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [41]:
#views vs copies
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [42]:
view[0]=200

In [43]:
arr

array([  1, 200,   3,   4,   5])

In [44]:
#copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [45]:
copy[0]=2
copy

array([2, 3])

In [46]:
arr

array([  1, 200,   3,   4,   5])

In [47]:
arr = np.array([[1,2],[3,4]])
# np.nditer is an efficient multi-dimensional iterator in NumPy.
# It allows you to iterate through every element of an array, 
# regardless of how many dimensions it has.
for x in np.nditer(arr):
    print(x)


1
2
3
4


In [48]:
arr = np.array([1,2,3])

v = arr.view()
c = arr.copy()

v[0] = 99
c[1] = 100

print(arr)  # only view affected


[99  2  3]


In [49]:
# np.ndenumerate allows iterating over an array while returning both the element’s index and value.
# It is useful when you need both the position and the item, especially in multi-dimensional arrays.”
import numpy as np

arr = np.array([[10, 20],
                [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)


(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40
