In [4]:
import numpy as np
arr = np.array([1,4,64,16])


In [5]:
# square root -> np.sqrt()
print(np.sqrt(arr))

[1. 2. 8. 4.]


In [6]:
#exponential - > np.exp -> e^x ->x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [7]:
#sine function -> np.sin
angles  = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [8]:
a = [1,2,3,4,5]


In [9]:
a[-1:-4]

[]

In [10]:
a[-1:-4:-1]

[5, 4, 3]

In [11]:
a[::2]

[1, 3, 5]

In [12]:
arr = np.array([10,20,30,40,50])
arr[::2] #slicing

array([10, 30, 50])

In [13]:
arr[-1]

50

In [14]:
print(arr[-1])

50


In [15]:
arr[-5]

10

In [16]:
arr[-1:-5]

array([], dtype=int32)

In [17]:
arr[-1:-4]

array([], dtype=int32)

In [18]:
arr[-1:-3]

array([], dtype=int32)

In [28]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


In [29]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [30]:
print(matrix[1:3 ,:])

[[4 5 6]
 [7 8 9]]


In [31]:
print(matrix[1: ,1:])

[[5 6]
 [8 9]]


In [37]:
#np.take -> bulit in function  to perrom indexing and slicing
arr= np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr,ind))


[10 30]


In [38]:
#iterating with  nditer()
arr = np.array([[1,2],[3,4]])


In [39]:
for x in np.nditer(arr):
    print(x,end = " ")

1 2 3 4 

In [48]:
# ndenumerate() -> both index +value
for ind, x in np.ndenumerate(arr):
    print(ind, x)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [49]:
#views vs copies
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [50]:
view[0]=200

In [51]:
arr

array([  1, 200,   3,   4,   5])

In [52]:
#copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [53]:
copy[0]=2
copy

array([2, 3])

In [54]:
arr

array([  1, 200,   3,   4,   5])

In [55]:
arr = np.array([[1,2],[3,4]])
# np.nditer is an efficient multi-dimensional iterator in NumPy.
# It allows you to iterate through every element of an array, 
# regardless of how many dimensions it has.
for x in np.nditer(arr):
    print(x)


1
2
3
4


In [56]:
arr = np.array([1,2,3])

v = arr.view()
c = arr.copy()

v[0] = 99
c[1] = 100

print(arr)  # only view affected


[99  2  3]


In [57]:
# np.ndenumerate allows iterating over an array while returning both the element’s index and value.
# It is useful when you need both the position and the item, especially in multi-dimensional arrays.”
import numpy as np

arr = np.array([[10, 20],
                [30, 40]])

for index, value in np.ndenumerate(arr):
    print(index, value)


(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40
