In [8]:
# np.vectorize()


import numpy as np
arr = np.array([3,5,7,3,7,2,8])



In [9]:
def square(x):
    return x*x
vfunc = np.vectorize(square)
  

In [10]:
arr

array([3, 5, 7, 3, 7, 2, 8])

In [11]:
print(vfunc(arr))

[ 9 25 49  9 49  4 64]


In [2]:
import numpy as np
a = np.array([2,4,6,8])

res = a*2
print(res)

[ 4  8 12 16]


In [3]:
a>4

array([False, False,  True,  True])

In [4]:
a**2

array([ 4, 16, 36, 64])